services:
  # lb:
  #   ip: 192.168.1.107
  #   ssh_port: 22000
  #   memory: 1024
  #   cpus: 2
  #   script: "Scripts/basic.sh"
  # app1:
  #   ip: 192.168.1.108
  #   ssh_port: 22001
  #   memory: 1024
  #   cpus: 2
  #   script: "Scripts/webserver_conf.sh"
  app2:
    ip: 192.168.1.109
    ssh_port: 22002
    memory: 1024
    cpus: 2
    script: "Scripts/basic.sh"
  # mariadb:
  #   ip: 192.168.1.110
  #   ssh_port: 22003
  #   memory: 1024
  #   cpus: 2
  #   script: "Scripts/basic.sh"
