- name: Ensure bind-address is commented out in system config
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: '#bind-address = 127.0.0.1'
    state: present
  notify: restart mariadb

- name: Deploy custom configuration
  ansible.builtin.template:
    src: 99-custom.cnf.j2
    dest: "{{ mariadb_config_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart mariadb
