---
- name: Create database
  ansible.mysql.mysql_db:
    name: "mariadb_name"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create user and grant privileges
  ansible.mysql.mysql_user:
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_name }}.*:ALL"
    host: "{{ mariadb_allowed_host }}"
    state: present
    login_unix_socket: "{{ mariadb_socket }}"
