---
- name: Deploy Gunicorn service
  ansible.builtin.template:
    src: flaskapp.service.j2
    dest: "/etc/systemd/system/{{ app_name }}.service"
    mode: "0644"
  notify:
  - reload systemd
  - restart gunicorn

- name: Enable and start Gunicorn
  ansible.builtin.systemd:
    name: "{{ app_name }}"
    enabled: true
    state: started
