---
- name: Create Python virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv {{ venv_dir }}
    creates: "{{ venv_dir }}/bin/activate"

- name: Install Python dependencies
  ansible.builtin.pip:
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ venv_dir }}"
  notify: restart gunicorn

- name: Install Gunicorn
  ansible.builtin.pip:
    name: gunicorn
    virtualenv: "{{ venv_dir }}"
