- name: Dependencies instalation
  ansible.builtin.pip:
    requirements: "{{ app_dir }}/BirdWatchingApp/requirements.txt"
    virtualenv: "{{ app_dir }}/BirdWatchingApp/venv"
    virtualenv_command: python3 -m venv
  become: true
  become_user: "{{ user }}"