web:
  hosts:
    app2:
      ansible_host: 172.20.10.10
    app1:
      ansible_host: 172.20.10.9

lbs:
  hosts:
    lb:
      ansible_host: 192.168.1.107

db:
  hosts:
    mariadb:
      ansible_host: 172.20.10.11

allhosts:
  children:
    wss:
    lbs:
    db:
  vars:
    ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id-rsa