---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart gunicorn
  ansible.builtin.service:
    name: "{{ app_name }}"
    state: restarted

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
